services:
  fastapi_app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .dev.env
    ports:
      - "5000:5000"
    depends_on:
      fastapi_db:
        condition: service_healthy
    networks:
      - backend

  fastapi_db:
    container_name: fastapi_db
    image: postgres:12.0-alpine
    hostname: fastapi_db
    env_file:
      - .db.env
    expose:
      - 5432
    networks:
      - backend
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 3

networks:
  backend: