name: Test CD Workflow

on:
    push:
    pull_request:

env:
  SQLALCHEMY_DATABASE_URL: postgresql://postgres:${{ secrets.TEST_POSTGRES_PASSWORD }}@localhost:5432/postgres

jobs:
    run-tests:
        name: Test
        runs-on: ubuntu-latest
        
        services:
          postgres:
            image: postgres
            env:
              POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
            options: >-
              --health-cmd pg_isready
              --health-interval 3s
              --health-timeout 3s
              --health-retries 5
              --name postgres_test
            ports:
              - 5432:5432 
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            
            - name: Install Dependencies
              run: |
                python3 -m pip install poetry
                python3 -m poetry config virtualenvs.create false
                python3 -m poetry install
            
            - name: Run tests
              run: pytest