name: Test CD Workflow

on:
    push:
    pull_request:

jobs:
    run-tests:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix: 
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version:
                    - 3.8
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Install Dependencies
              run: |
                python3 -m pip install poetry
                python3 -m poetry config virtualenvs.create false
                python3 -m poetry install
            
            - name: Run tests
              run: pytest